name: Build and Test CMake project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Tämä voi olla myös windows-latest tai macos-latest

    steps:
    # 1. Checkout-koodi
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Asenna CMake (manuaalisesti)
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    # 3. Asenna riippuvuudet, kuten gtest, jos niitä tarvitaan
    - name: Install dependencies
      run: sudo apt-get install libgtest-dev

    # 4. Käännä projekti
    - name: Build with CMake
      run: cmake -S . -B build  # Käyttää nykyistä hakemistoa (S) ja luo build-hakemiston

    # 5. Suorita testit, jos käytät testauskehystä, kuten Google Test
    - name: Run tests
      run: ctest --output-on-failure
